ALTER TABLE HangFire.JobParameter  WITH CHECK ADD  CONSTRAINT FK_HangFire_JobParameter_Job FOREIGN KEY (JobId)
REFERENCES HangFire.Job (Id)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE HangFire.JobParameter CHECK CONSTRAINT FK_HangFire_JobParameter_Job
GO

ALTER TABLE HangFire.State  WITH CHECK ADD  CONSTRAINT FK_HangFire_State_Job FOREIGN KEY (JobId)
REFERENCES HangFire.Job (Id)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE HangFire.State CHECK CONSTRAINT FK_HangFire_State_Job
GO
