name: ci

on: [push]

jobs:
    ubuntu-latest:
        name: ubuntu-latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run './build.cmd Compile'
              run: ./build.cmd CI
            - name: run dotnet test
              uses: zyborg/dotnet-tests-report@v1
              with:
                  project_path: ${{ github.workspace }}/MSDF.DataChecker.sln
                  report_name: ubuntu_data_checker_tests
                  report_title: DataChecker Tests (Ubuntu)
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  gist_name: ubuntu_data_checker_tests.md
                  gist_badge_label: "DataChecker Tests: %Counters_passed%/%Counters_total%"
                  gist_token: ${{ secrets.GIST_TOKEN }}
                  no_restore: true
                  set_check_status_from_test_outcome: true
            - name: Run './build.cmd CI_UI'
              run: ./build.cmd CI_UI
    windows-latest:
        name: windows-latest
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run './build.cmd CI'
              run: ./build.cmd CI
            - name: run dotnet test
              uses: zyborg/dotnet-tests-report@v1
              with:
                  project_path: ${{ github.workspace }}/MSDF.DataChecker.sln
                  report_name: windows_data_checker_tests
                  report_title: DataChecker Tests (Windows)
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  gist_name: windows_data_checker_tests.md
                  gist_badge_label: "DataChecker Tests: %Counters_passed%/%Counters_total%"
                  gist_token: ${{ secrets.GIST_TOKEN }}
                  no_restore: true
                  set_check_status_from_test_outcome: true
            - name: Run './build.cmd CI_UI'
              run: ./build.cmd CI_UI

    macOS-latest:
        name: macOS-latest
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run './build.cmd CI'
              run: ./build.cmd CI
            - name: run dotnet test
              uses: zyborg/dotnet-tests-report@v1
              with:
                  project_path: ${{ github.workspace }}/MSDF.DataChecker.sln
                  report_name: macos_data_checker_tests
                  report_title: DataChecker Tests (MacOS)
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  gist_name: macos_data_checker_tests.md
                  gist_badge_label: "DataChecker Tests: %Counters_passed%/%Counters_total%"
                  gist_token: ${{ secrets.GIST_TOKEN }}
                  no_restore: true
                  set_check_status_from_test_outcome: true
            - name: Run './build.cmd CI_UI'
              run: ./build.cmd CI_UI
